[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
base64 = "0.21.7"
itertools = "0.12.1"
once_cell = "1.19.0"
openssl = "0.10.63"
rand = "0.8.5"
